# Jellyfin is a Free Software Media System that puts you in control of managing and streaming your media. It is an alternative to the proprietary Emby and Plex, to provide media from a dedicated server to end-user devices via multiple apps.
# Jellyfin is descended from Emby's 3.5.2 release and ported to the .NET Core framework to enable full cross-platform support. There are no strings attached, no premium licenses or features, and no hidden agendas: just a team who want to build something better and work together to achieve it.
#
# ðŸ  Home: https://jellyfin.org/  
# ðŸ“¦ Image: https://hub.docker.com/r/linuxserver/jellyfin  
#
# Desktop client: https://github.com/jellyfin/jellyfin-media-player  
---
name: jellyfin
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.9.10
    container_name: jellyfin
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
      JELLYFIN_PublishedServerUrl: ${MAIN_NODE_IP}
    volumes:
      - ${DOCKER_VOLUMES}/jellyfin:/config
      - ${STORAGE_MEDIA}:/media:ro
      - ${STORAGE_FAMILYMEDIA}:/family-media:ro
    # https://jellyfin.org/docs/general/networking/
    ports:
      - 8096:8096 # Web UI - HTTP
      - 8920:8920 # Web UI - HTTPS
      - 7359:7359/udp # Auto-discovery
      # - 1900:1900/udp # Service auto-discovery, DLNA - TODO enable
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.jellyfin.entrypoints: websecure
      traefik.http.routers.jellyfin.middlewares: https-public@file
      traefik.http.services.jellyfin.loadbalancer.server.port: 8096
      homepage.group: Media
      homepage.name: Jellyfin
      homepage.icon: jellyfin.png
      homepage.href: https://jellyfin.${MYDOMAIN}/
      homepage.description: Media Management
      # homepage.widget.type: jellyfin
      # homepage.widget.url: https://jellyfin.${MYDOMAIN}
      # You can create an API key from inside Jellyfin at Settings > Advanced > API Keys.
      # homepage.widget.key: ${JELLYFIN_API_KEY}

networks:
  proxy:
    external: true
