# Portainer Community Edition is a lightweight service delivery platform for containerized applications that can be used to manage Docker, Swarm, Kubernetes and ACI environments.
# It is designed to be as simple to deploy as it is to use. The application allows you to manage all your orchestrator resources (containers, images, volumes, networks and more) through a ‘smart’ GUI and/or an extensive API.
#
# Portainer uses the Portainer Agent container to communicate with the Portainer Server instance and provide access to the node's resources.
#
# Links:
# - Home: https://www.portainer.io/
# - Source: https://github.com/portainer/portainer
---
name: portainer-agent
services:
  agent:
    image: portainer/agent:2.39.0
    container_name: portainer-agent
    ports:
      - 9001:9001
    # kics-scan ignore-block
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: always
