# Bazarr is a companion application to Sonarr and Radarr. It can manage and download subtitles based on your requirements.
# You define your preferences by TV show or movie and Bazarr takes care of everything for you.
#
# Links:
# - Home: https://www.bazarr.media/
# - Image: https://hub.docker.com/r/linuxserver/bazarr
---
name: bazarr
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:1.5.6
    container_name: bazarr
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ${DOCKER_VOLUMES}/bazarr/config:/config
      - ${STORAGE_MEDIA}:/media
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.bazarr.middlewares: localaccess@file
      traefik.http.services.bazarr.loadbalancer.server.port: 6767
      homepage.group: Arr
      homepage.name: Bazarr
      homepage.icon: bazarr.png
      homepage.href: https://bazarr.${MYDOMAIN}/
      homepage.description: Manage and download subtitles

networks:
  proxy:
    external: true
