# Minimal Jupyter Notebook Python Stack
#
# Show login token: `jupyter server list` (run inside the container)
#
# TODO setup permanent password: https://jupyter-server.readthedocs.io/en/latest/operators/public-server.html#automatic-password-setup
#
# Links:
# - Home: https://jupyter-docker-stacks.readthedocs.io/en/latest/index.html
# - Source: https://github.com/jupyter/docker-stacks
# - Image: https://quay.io/repository/jupyter/minimal-notebook
---
name: jupyter-notebook
services:
  jupyter-notebook:
    image: quay.io/jupyter/minimal-notebook:notebook-7.2.2
    container_name: jupyter-notebook
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ${DOCKER_VOLUMES}/jupyter-notebook:/home/jovyan
    labels:
      traefik.enable: true
      traefik.http.routers.jupyter-notebook.middlewares: localaccess@file
      traefik.http.routers.jupyter-notebook.rule: Host(`jupyter.${MYDOMAIN}`)
      traefik.http.services.jupyter-notebook.loadbalancer.server.port: 8888
      homepage.group: Development
      homepage.name: Jupyter Notebook
      homepage.icon: jupyter.png
      homepage.href: https://jupyter.${MYDOMAIN}/
      homepage.description: Minimal Jupyter Notebook Python Stack

networks:
  proxy:
    external: true
