# Code-server is VS Code running on a remote server, accessible through the browser.
#
# Links:
# - Home: https://coder.com/
# - Image: https://hub.docker.com/r/linuxserver/code-server
# - Source: https://github.com/coder/code-server
# - FAQ: https://github.com/coder/code-server/blob/main/docs/FAQ.md
#
# Alternative: OpenVSCode Server
# - https://github.com/gitpod-io/openvscode-server
# - https://docs.linuxserver.io/images/docker-openvscode-server/
---
name: code-server
services:
  code-server:
    image: lscr.io/linuxserver/code-server:4.108.1
    container_name: code-server
    hostname: code-server
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
      PASSWORD: # optional
      HASHED_PASSWORD: # optional
      SUDO_PASSWORD: ${ADMIN_PASSWORD} # optional
      SUDO_PASSWORD_HASH:  # optional
      PROXY_DOMAIN: code.${MYDOMAIN} # optional
      DEFAULT_WORKSPACE: /config/workspace # optional
    volumes:
      - ${DOCKER_VOLUMES}/code-server:/config
      - ${ADMIN_HOME}/repos:/config/repos
      - ${ADMIN_HOME}/.ssh:/config/.ssh
    networks:
      - dev-code-server
    labels:
      traefik.enable: true
      traefik.docker.network: dev-code-server
      traefik.http.routers.code.middlewares: localaccess-sso@file
      traefik.http.routers.code.rule: Host(`code.${MYDOMAIN}`)
      traefik.http.services.code.loadbalancer.server.port: 8443
      homepage.group: Development
      homepage.name: Code-Server
      homepage.icon: code.png
      homepage.href: https://code.${MYDOMAIN}/
      homepage.description: "[SSO] Visual Studio Code"

networks:
  dev-code-server:
    external: true
