# Readarr - Book Manager and Automation (Sonarr for Ebooks)
#
# Quick start guide: https://wiki.servarr.com/readarr/quick-start-guide
#
# Links:
# - Home: https://readarr.com/
# - Source: https://github.com/Readarr/Readarr
# - Image: https://docs.linuxserver.io/images/docker-readarr/
#
# TODO: Replace this service
# > **Announcement: Retirement of Readarr**
# > We would like to announce that the Readarr project has been retired. This difficult decision was made due to a combination of factors: the project's metadata has become unusable, we no longer have the time to remake or repair it, and the community effort to transition to using Open Library as the source has stalled without much progress.
---
name: readarr
services:
  readarr:
    image: lscr.io/linuxserver/readarr:nightly
    container_name: readarr
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ${DOCKER_VOLUMES}/readarr:/config
      - ${STORAGE_CALIBRE_LIBRARY}:/books
      - ${STORAGE_TORRENT_DOWNLOADS}:/downloads
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.readarr.middlewares: localaccess@file
      traefik.http.services.readarr.loadbalancer.server.port: 8787
      homepage.group: Arr
      homepage.name: Readarr
      homepage.icon: readarr.png
      homepage.href: https://readarr.${MYDOMAIN}/
      homepage.description: Download books

networks:
  proxy:
    external: true
